Provide a better error message when a compiler binary isn't found

diff --git a/junixsocket-native/crossclang/bin/clang b/junixsocket-native/crossclang/bin/clang
--- a/junixsocket-native/crossclang/bin/clang
+++ b/junixsocket-native/crossclang/bin/clang
@@ -408,11 +408,17 @@ if [[ $gccMode -eq 1 ]]; then
 fi
 
 
+compilerBinary="$(which $compiler)"
+if [ -z "$compilerBinary" ]; then
+  echo "Cannot compile -- compiler not found: $compiler" >&2
+  exit 1
+fi
+
 # set -x
 if [[ $withAndWithoutLC -eq 1 ]]; then
   nodepsOut="${outputFile%.*}.nodeps.${outputFile##*.}"
-  $(which $compiler) ${isystem_decls[@]} ${clangLinkerArgs[@]} -lc ${output_args[@]} ${clangArgs[@]} ${libsArgs[@]} && \
-  $(which $compiler) ${isystem_decls[@]} ${clangLinkerArgs[@]} -nostdlib -o "$nodepsOut" ${clangArgs[@]} ${libsArgs[@]}
+  "$compilerBinary" ${isystem_decls[@]} ${clangLinkerArgs[@]} -lc ${output_args[@]} ${clangArgs[@]} ${libsArgs[@]} && \
+  "$compilerBinary" ${isystem_decls[@]} ${clangLinkerArgs[@]} -nostdlib -o "$nodepsOut" ${clangArgs[@]} ${libsArgs[@]}
 else
-  exec $(which $compiler) ${isystem_decls[@]} ${clangLinkerArgs[@]} ${output_args[@]} ${clangArgs[@]} ${libsArgs[@]}
+  exec "$compilerBinary" ${isystem_decls[@]} ${clangLinkerArgs[@]} ${output_args[@]} ${clangArgs[@]} ${libsArgs[@]}
 fi
